// This file is auto-generated by scripts/scenar-backstage/generate-scenar-registry.mjs
// Do not edit manually.
import type { ScenarioEntry, ScenarioInputOverrides, ScenarioRegistry } from './scenario-types';
import type { ScenarioInputParser } from './scenario-parsers';
import { scenarioParseBoolean, scenarioParseEnum, scenarioParseString } from './scenario-parsers';

function mergeInputs(
  autoInputs: Record<string, ScenarioInputParser>,
  overrides: ScenarioInputOverrides | undefined
): Record<string, ScenarioInputParser> {
  if (!overrides) return autoInputs;
  const merged: Record<string, ScenarioInputParser> = { ...autoInputs };
  for (const [key, value] of Object.entries(overrides)) {
    if (value === false) {
      delete merged[key];
      continue;
    }
    merged[key] = value;
  }
  return merged;
}

const autoInputs0 = {
  "label": (raw: string) => scenarioParseString(raw),
  "disabled": (raw: string) => scenarioParseBoolean(raw),
  "loading": (raw: string) => scenarioParseBoolean(raw),
  "variant": scenarioParseEnum(["primary", "secondary", "tertiary", "danger", "ghost"]),
  "size": scenarioParseEnum(["xs", "sm", "md", "lg"]),
  "type": scenarioParseEnum(["button", "submit", "reset"]),
  "fullWidth": (raw: string) => scenarioParseBoolean(raw),
  "ariaLabel": (raw: string) => scenarioParseString(raw),
  "iconStart": (raw: string) => scenarioParseString(raw),
  "iconEnd": (raw: string) => scenarioParseString(raw),
} as const;

const entry0: ScenarioEntry = {
  id: "coar-button",
  loadComponent: async () => {
    const mod = await import("./scenarios/coar-button/coar-button.component");
    return mod.CoarButtonScenarioComponent;
  },
  providers: undefined,
  inputs: mergeInputs(autoInputs0, undefined),
};

const autoInputs1 = {
  "triggerLabel": (raw: string) => scenarioParseString(raw),
  "content": (raw: string) => scenarioParseString(raw),
  "disabled": (raw: string) => scenarioParseBoolean(raw),
  "openOnHover": (raw: string) => scenarioParseBoolean(raw),
  "openOnClick": (raw: string) => scenarioParseBoolean(raw),
  "interactive": (raw: string) => scenarioParseBoolean(raw),
} as const;

const entry1: ScenarioEntry = {
  id: "coar-popover",
  loadComponent: async () => {
    const mod = await import("./scenarios/coar-popover/coar-popover.component");
    return mod.CoarPopoverScenarioComponent;
  },
  providers: undefined,
  inputs: mergeInputs(autoInputs1, undefined),
};

const registry: ScenarioRegistry = {
  [entry0.id]: entry0,
  [entry1.id]: entry1,
};

export const SCENARIO_REGISTRY: ScenarioRegistry = Object.freeze(registry);
