// This file is auto-generated by scripts/component-test-host/generate-ct-registry.mjs
// Do not edit manually.
import type { CtEntry, CtInputOverrides, CtRegistry } from './ct-types';
import type { CtInputParser } from './ct-parsers';
import { ctParseBoolean, ctParseEnum, ctParseString } from './ct-parsers';

function mergeInputs(
  autoInputs: Record<string, CtInputParser>,
  overrides: CtInputOverrides | undefined
): Record<string, CtInputParser> {
  if (!overrides) return autoInputs;
  const merged: Record<string, CtInputParser> = { ...autoInputs };
  for (const [key, value] of Object.entries(overrides)) {
    if (value === false) {
      delete merged[key];
      continue;
    }
    merged[key] = value;
  }
  return merged;
}

const autoInputs0 = {
  label: (raw: string) => ctParseString(raw),
  disabled: (raw: string) => ctParseBoolean(raw),
  loading: (raw: string) => ctParseBoolean(raw),
  variant: ctParseEnum(['primary', 'secondary', 'tertiary', 'danger', 'ghost']),
  size: ctParseEnum(['xs', 'sm', 'md', 'lg']),
  type: ctParseEnum(['button', 'submit', 'reset']),
  fullWidth: (raw: string) => ctParseBoolean(raw),
  ariaLabel: (raw: string) => ctParseString(raw),
  iconStart: (raw: string) => ctParseString(raw),
  iconEnd: (raw: string) => ctParseString(raw),
} as const;

const entry0: CtEntry = {
  id: 'coar-button',
  loadComponent: async () => {
    const mod = await import('./stories/coar-button-story/coar-button-story.component');
    return mod.CoarButtonStoryComponent;
  },
  providers: undefined,
  inputs: mergeInputs(autoInputs0, undefined),
};

const autoInputs1 = {
  triggerLabel: (raw: string) => ctParseString(raw),
  content: (raw: string) => ctParseString(raw),
  disabled: (raw: string) => ctParseBoolean(raw),
  openOnHover: (raw: string) => ctParseBoolean(raw),
  openOnClick: (raw: string) => ctParseBoolean(raw),
  interactive: (raw: string) => ctParseBoolean(raw),
} as const;

const entry1: CtEntry = {
  id: 'coar-popover',
  loadComponent: async () => {
    const mod = await import('./stories/coar-popover-story/coar-popover-story.component');
    return mod.CoarPopoverStoryComponent;
  },
  providers: undefined,
  inputs: mergeInputs(autoInputs1, undefined),
};

const registry: CtRegistry = {
  [entry0.id]: entry0,
  [entry1.id]: entry1,
};

export const CT_REGISTRY: CtRegistry = Object.freeze(registry);
